swagger: "2.0"
info:
  version: "0.1.0"
  title: Tlks.io API
  host: api.tlks.io
  basePath: /
  schemes:
    - http
  consumes:
    - application/json
  produces:
    - application/json
  paths:
    /teapot:
      x-swagger-router-controller: teapot
      get:
        description: Returns 418 HTTP code to the caller
        operationId: teapot
        responses:
          "418":
            description: I'm a teapot
